{"cells":[{"cell_type":"markdown","metadata":{"id":"PeuakI3rgoQe"},"source":["# Excepciones\n","\n","Una **excepción** es el código que se ejecuta cuando se produce un error en nuestro programa Python durante la fase de ejecución.\n","\n","De hecho ya hemos visto algunas de estas excepciones: accesos fuera de rango a listas o tuplas, accesos a claves inexistentes en diccionarios, etc. Cuando ejecutamos código que podría fallar bajo ciertas circunstancias necesitamos también *manejar las excepciones* de manera adecuada.\n","\n","Si una excepción ocurre en una función y no es capturada en ese punto, va subiendo (*burbujeando*) hasta que es capturada en alguna función que ha hecho la llamada. Si en toda la \"pila\" de llamadas no existe un control de la excepción, Python muestra un mensaje de error con información adicional."]},{"cell_type":"markdown","metadata":{"id":"gCq5_3h7ZuMI"},"source":["### Ejemplos\n"]},{"cell_type":"markdown","metadata":{"id":"00rtNZwqZuMI"},"source":["Ejecuta cada trozo de código y observa la excepción que aparece\n"]},{"cell_type":"code","execution_count":1,"metadata":{"id":"hE0jxbKrZuMJ","colab":{"base_uri":"https://localhost:8080/","height":169},"executionInfo":{"status":"error","timestamp":1667230802294,"user_tz":-60,"elapsed":14,"user":{"displayName":"Andrea Ramirez Burgos","userId":"06052113304131249114"}},"outputId":"ef9a26d4-c3b6-4329-f13a-adad22bb3724"},"outputs":[{"output_type":"error","ename":"ZeroDivisionError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-1-9e1622b385b6>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;36m1\u001b[0m\u001b[0;34m/\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"]}],"source":["1/0"]},{"cell_type":"markdown","metadata":{"id":"PUaOf0ubZuMK"},"source":["<code>ZeroDivisionError</code> ocurre cuando intentas dividir por cero\n"]},{"cell_type":"code","execution_count":2,"metadata":{"id":"H7it2GktZuML","colab":{"base_uri":"https://localhost:8080/","height":169},"executionInfo":{"status":"error","timestamp":1667230812636,"user_tz":-60,"elapsed":14,"user":{"displayName":"Andrea Ramirez Burgos","userId":"06052113304131249114"}},"outputId":"1c09c064-99a6-4a1a-afb0-a08635b0a98f"},"outputs":[{"output_type":"error","ename":"NameError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-2-6ddcec040107>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0my\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0ma\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;36m5\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mNameError\u001b[0m: name 'a' is not defined"]}],"source":["y = a + 5"]},{"cell_type":"markdown","metadata":{"id":"vFtpqs10ZuML"},"source":["<code>NameError</code> -- en este caso, significa que has intentado usar una variable que no está definida\n"]},{"cell_type":"code","execution_count":3,"metadata":{"id":"J1q36gQ6ZuMM","colab":{"base_uri":"https://localhost:8080/","height":187},"executionInfo":{"status":"error","timestamp":1667230820958,"user_tz":-60,"elapsed":945,"user":{"displayName":"Andrea Ramirez Burgos","userId":"06052113304131249114"}},"outputId":"462dd254-6573-44af-e2d8-0e29df87ed1b"},"outputs":[{"output_type":"error","ename":"IndexError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)","\u001b[0;32m<ipython-input-3-3f911ca4e3d3>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0ma\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m2\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m3\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0ma\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m10\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mIndexError\u001b[0m: list index out of range"]}],"source":["a = [1, 2, 3]\n","a[10]"]},{"cell_type":"markdown","metadata":{"id":"AYt3bEZyZuMM"},"source":["<code>IndexError</code> -- en este caso, ocurre porque se intenta acceder a datos de una lista usando un índice que no existe para esa lista.\n"]},{"cell_type":"markdown","metadata":{"id":"QxH3JssmZuMN"},"source":["Hay muchas más excepciones integradas en Python, aquí hay una lista de ellas [https://docs.python.org/3/library/exceptions.html](https://docs.python.org/3/library/exceptions.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0101ENSkillsNetwork19487395-2021-01-01)\n"]},{"cell_type":"markdown","metadata":{"id":"a1jzAm_zZuMN"},"source":["## Manejo de Excepciones\n"]},{"cell_type":"markdown","metadata":{"id":"6BYMdXz0ZuMN"},"source":["En esta sección aprenderás a manejar las excepciones. Comprenderás cómo hacer que tu programa realice tareas específicas en lugar de detener la ejecución del código cuando se encuentra una excepción.\n"]},{"cell_type":"markdown","metadata":{"id":"aCLEJ7MsZuMO"},"source":["### Try Except\n"]},{"cell_type":"markdown","metadata":{"id":"qy6g1BFYZuMO"},"source":["Un <code>try except</code> te permitirá ejecutar código que podría generar una excepción y, en caso de cualquier excepción o una específica, podemos manejar o capturar la excepción y ejecutar código específico. Esto nos permitirá continuar con la ejecución del programa incluso si hay una excepción.\n","\n","Python intenta ejecutar el código en el bloque <code>try</code>. En este caso, si hay alguna excepción provocada por el código dentro del <code>try</code>, se detectará y se ejecutará el código del bloque <code>except</code>. Después de eso, se ejecutará el código que viene <em>después</em> del try except.\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"0LKN7WlMZuMO"},"outputs":[],"source":["# Posible código antes del try catch\n","\n","try:\n","    # código que se intenta ejecutar\n","except:\n","    # código que se ejecuta si hay una excepción\n","    \n","# código que se ejecutará haya o no haya un excepción"]},{"cell_type":"markdown","metadata":{"id":"erClvxZ3ZuMP"},"source":["### Ejemplo Try Except\n"]},{"cell_type":"markdown","metadata":{"id":"bAXew-0aZuMP"},"source":["En este ejemplo, estamos tratando de dividir un número dado por el usuario, guardar el resultado en la variable <code>a</code> y luego nos gustaría imprimir el resultado de la operación. Al recoger lo que ha escrito el usuario y dividir un número por ello, hay varias excepciones que pueden surgir. Por ejemplo si dividimos por cero. Intenta ejecutar el siguiente bloque de código con <code>b</code> como número. Solo se generará una excepción si <code>b</code> es cero.\n"]},{"cell_type":"code","execution_count":5,"metadata":{"id":"Q3oKqOCpZuMP","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1667230975455,"user_tz":-60,"elapsed":3048,"user":{"displayName":"Andrea Ramirez Burgos","userId":"06052113304131249114"}},"outputId":"ee660b3d-57cc-4372-8e4e-b90aadec8194"},"outputs":[{"output_type":"stream","name":"stdout","text":["Por favor introduce un número para dividir a0\n","Ha habido un error\n"]}],"source":["a = 1\n","\n","try:\n","    b = int(input(\"Por favor introduce un número para dividir a\"))\n","    a = a/b\n","    print(\"Éxito a=\",a)\n","except:\n","    print(\"Ha habido un error\")\n","        \n"]},{"cell_type":"markdown","metadata":{"id":"OhcGFnzPZuMQ"},"source":["### Try Except Específico\n"]},{"cell_type":"markdown","metadata":{"id":"Lw4rQSXrZuMQ"},"source":["Un <code>try except</code> específico te permite capturar excepciones concretas y ejecutar cierto código dependiendo de la excepción. Esto es útil si no quieres tratar con algunas excepciones y la ejecución deberá detenerse. También puede ayudarte a encontrar errores en el código de los que quizás no estés al tanto. Además, puede ayudarte a diferenciar las respuestas a diferentes excepciones. En este caso, es posible que el código después de la excepción de prueba no se ejecute según el error.\n"]},{"cell_type":"markdown","metadata":{"id":"KKqwjZlMZuMQ"},"source":["<b>No lo ejecutes, solo es para ilustrar:</b>\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"sMUlt4vcZuMR"},"outputs":[],"source":["# Posible código antes del try catch\n","\n","\n","try:\n","    # código que se intenta ejecutar\n","except (ZeroDivisionError, NameError):\n","    # código que se ejecuta si hay una excepción de los tipos dados\n","    \n","# código que se ejecutará si no hay un excepción o una de las que estamos manejando"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"Th4WK6DuZuMR"},"outputs":[],"source":["# Posible código antes del try catch\n","\n","\n","try:\n","    # código que se intenta ejecutar\n","except ZeroDivisionError:\n","    # código que se ejecuta si hay un ZeroDivisionError\n","except NameError:\n","    # código que se ejecuta si hay un NameError\n","    \n","# código que se ejecutará si no hay una excepción o una de las que estamos manejando"]},{"cell_type":"markdown","metadata":{"id":"CSpHfE1GZuMS"},"source":["También puede tener un <code>except</code> vacío al final para detectar una excepción inesperada:\n"]},{"cell_type":"markdown","metadata":{"id":"aFuQ7iCsZuMS"},"source":["<b>No lo ejecutes, solo es para ilustrar:</b>\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"SQoYcUowZuMS"},"outputs":[],"source":["# Posible código antes del try catch\n","\n","try:\n","    # código que se intenta ejecutar\n","except ZeroDivisionError:\n","    # código que se ejecuta si hay un ZeroDivisionError\n","except NameError:\n","    # código que se ejecuta si hay un NameError\n","except:\n","    # código que se ejecuta si hay alguna excepción\n","    \n","# código que se ejecutará si no hay una excepción o una de las que estamos manejando"]},{"cell_type":"markdown","metadata":{"id":"KX0296gaZuMS"},"source":["### Ejemplo de Try Except Específico\n"]},{"cell_type":"markdown","metadata":{"id":"Yj1kAzlPZuMS"},"source":["Este es el mismo ejemplo que el anterior, pero ahora añadiremos diferentes mensajes según la excepción, para que el usuario sepa cuál es el problema con lo que ha escrito.\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"P_Wog0VrZuMT"},"outputs":[],"source":["a = 1\n","\n","try:\n","    b = int(input(\"Por favor introduce un número para dividir a\"))\n","    a = a/b\n","    print(\"Éxito a=\",a)\n","except ZeroDivisionError:\n","    print(\"El número introducido no puede dividir 1 porque es 0\")\n","except ValueError:\n","    print(\"No has introducido un número\")\n","except:\n","    print(\"Algo salió mal\")\n","        \n"]},{"cell_type":"markdown","metadata":{"id":"W8KM_mARZuMT"},"source":["### Try Except Else y Finally\n"]},{"cell_type":"markdown","metadata":{"id":"GS3VAv2JZuMT"},"source":["<code>else</code> permite verificar si no hubo excepciones al ejecutar el bloque try. Esto es útil cuando queremos ejecutar algo solo si no hubo errores.\n"]},{"cell_type":"markdown","metadata":{"id":"D0OcFMP5ZuMT"},"source":["<b>No lo ejecutes, solo es para ilustrar:</b>\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"C7WYJeWmZuMU"},"outputs":[],"source":["# Posible código antes del try catch\n","\n","try:\n","    # código que se intenta ejecutar\n","except ZeroDivisionError:\n","    # código que se ejecuta si hay un ZeroDivisionError\n","except NameError:\n","    # código que se ejecuta si hay un NameError\n","except:\n","    # código que se ejecuta si hay alguna excepción\n","else:\n","    # código que se ejecuta si no hay ninguna excepción\n","    \n","# código que se ejecutará si no hay un excepción o una de las que estamos manejando"]},{"cell_type":"markdown","metadata":{"id":"mbXIGZC7ZuMU"},"source":["<code>finally</code> nos permite ejecutar algo siempre, haya una excepción o no. Esto se usa generalmente para indicar el final del try except.\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"NFkA7l0oZuMU"},"outputs":[],"source":["# Posible código antes del try catch\n","\n","try:\n","    # código que se intenta ejecutar\n","except ZeroDivisionError:\n","    # código que se ejecuta si hay un ZeroDivisionError\n","except NameError:\n","    # código que se ejecuta si hay un NameError\n","except:\n","    # código que se ejecuta si hay alguna excepción\n","else:\n","    # código que se ejecuta si no hay ninguna excepción\n","finally:\n","    # código que se ejecuta al terminar el try except pase lo que pase\n","    \n","# código que se ejecutará si no hay un excepción o una de las que estamos manejando"]},{"cell_type":"markdown","metadata":{"id":"Yx9jdDauZuMV"},"source":["### Ejemplo de Try Except Else y Finally\n"]},{"cell_type":"markdown","metadata":{"id":"pISY1gcXZuMV"},"source":["Es posible que hayas notado que incluso si hay un error, el valor de <code>a</code> siempre se imprime. Vamos a usar el <code>else</code> e imprimiremos el valor de <code>a</code> solo si no hay error.\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"peX9nQdOZuMV"},"outputs":[],"source":["a = 1\n","\n","try:\n","    b = int(input(\"Por favor introduce un número para dividir a\"))\n","    a = a/b\n","except ZeroDivisionError:\n","    print(\"El número introducido no puede dividir 1 porque es 0\")\n","except ValueError:\n","    print(\"No has introducido un número\")\n","except:\n","    print(\"Algo salió mal\")\n","else:\n","    print(\"Éxito a=\",a)"]},{"cell_type":"markdown","metadata":{"id":"g37CEsIbZuMV"},"source":["Ahora, informaremos al usuario de que hemos terminado de procesar su respuesta. Usando <code>finally</code>, añadiremos un print.\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"v0hlV500ZuMW"},"outputs":[],"source":["a = 1\n","\n","try:\n","    b = int(input(\"Please enter a number to divide a\"))\n","    a = a/b\n","except ZeroDivisionError:\n","    print(\"El número introducido no puede dividir 1 porque es 0\")\n","except ValueError:\n","    print(\"No has introducido un número\")\n","except:\n","    print(\"Algo salió mal\")\n","else:\n","    print(\"Éxito a=\",a)\n","finally:\n","    print(\"Proceso Completado\")"]},{"cell_type":"markdown","metadata":{"id":"lP0Kh4QxgoQg"},"source":["### Crear excepciones propias\n","\n","Todas las excepciones que hemos visto hasta ahora estaban ya predefinidas en el propio lenguaje o en la librería estándar. Pero es posible crear *excepciones propias* para manejar situaciones especiales que podrían producirse en nuestro código:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"bWyd5TH0goQg"},"outputs":[],"source":["class UppercaseException(Exception):\n","    pass"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"VNf7mlkSgoQg"},"outputs":[],"source":["words = ['chocolate', 'milk', 'TEA', 'water']"]},{"cell_type":"code","execution_count":6,"metadata":{"tags":["raises-exception"],"id":"Hchyq6WDgoQg","outputId":"b23158d7-3141-4ca1-d5f2-ec535fea258b","colab":{"base_uri":"https://localhost:8080/","height":205},"executionInfo":{"status":"error","timestamp":1667231298638,"user_tz":-60,"elapsed":258,"user":{"displayName":"Andrea Ramirez Burgos","userId":"06052113304131249114"}}},"outputs":[{"output_type":"error","ename":"NameError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-6-75fd7259d9f7>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mfor\u001b[0m \u001b[0mword\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mwords\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mword\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0misupper\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m         \u001b[0;32mraise\u001b[0m \u001b[0mUppercaseException\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mword\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mNameError\u001b[0m: name 'words' is not defined"]}],"source":["for word in words:\n","    if word.isupper():\n","        raise UppercaseException(word)"]},{"cell_type":"markdown","metadata":{"id":"OWmUmtKigoQh"},"source":["> Esta excepción propia también se puede gestionar con un `try...except`."]}],"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.7.6"},"colab":{"provenance":[{"file_id":"1yb6Jk_lYCFn998HDiOylhdSniXYystgx","timestamp":1667230788659}],"collapsed_sections":[]}},"nbformat":4,"nbformat_minor":0}